export const guides = [
  {
    slug: "theory-order",
    title: "Theory and International Order",
    eyebrow: "Conceptual frame",
    dek: "China's vocabulary of sovereignty, development, multilateralism, and reform of global governance.",
    thesis:
      "This guide tracks how official Chinese materials describe the existing international order: not as something to abandon wholesale, but as something to defend selectively, reform institutionally, and reinterpret through development, sovereign equality, and anti-hegemonic language.",
    overview: [
      "This topic introduces the conceptual vocabulary through which China explains its place in international law and world order. It follows ideas such as sovereign equality, multilateralism, democratization of international relations, a community of shared future, development-first governance, and opposition to hegemony.",
      "The materials are useful for separating legal argument from diplomatic ideology. Readers can compare white papers, speeches, UN positions, and scholarly commentary to see when China defends existing institutions, when it seeks reform, and when it uses alternative concepts to contest Western or liberal accounts of order.",
    ],
    questions: [
      "When does China invoke the existing order, and when does it call for reform?",
      "How do ideas such as a community of shared future translate into legal or institutional claims?",
      "Which concepts are doctrinal, and which are diplomatic or ideological?",
    ],
    featuredIds: [
      "prc-2023-global-community-shared-future",
      "prc-2023-global-governance-reform",
      "prc-2011-peaceful-development",
      "intl-1945-un-charter",
      "practice-2023-saudi-iran",
    ],
    readingIds: [
      "lit-xue-2012",
      "lit-cai-2019",
      "lit-johnston-2008",
      "lit-potter-2011",
      "lit-burnay-2018",
      "lit-kent-2007-beyond-compliance",
      "lit-2024-cambridge-handbook-china-intl-law",
      "lit-2024-springer-diplomacy-intl-law",
      "lit-2024-east-asia-multilateralism-soft-power-made-in-china",
      "lit-2021-chinesejil-community-shared-future-legalist-turn",
      "lit-2021-cjcl-global-constitutionalism-common-destiny-future-intl-law",
      "lit-2024-io-reconceptualizing-international-order",
      "lit-2025-ia-rising-states-liberal-order",
      "lit-2025-ia-beyond-liberal-narratives-human-rights-order",
      "lit-2025-eia-china-international-justice-research-agenda",
      "lit-2025-hague-foreign-related-rule-of-law",
      "lit-2025-upenn-international-legal-ordering",
      "lit-2025-jhil-china-unbounded-late-qing",
      "lit-2025-tclr-state-role-property-law",
      "lit-2025-columbia-moralizing-courts",
      "lit-2025-chinesejil-personal-data-ai",
      "lit-2025-chinesejil-practice-public-international-law-2022",
      "lit-2025-chinesejil-maritime-ambitions-bbnj",
      "lit-2025-ripe-multilateralism-a-la-carte",
      "lit-2026-ripe-institutional-layering-gdi",
      "lit-2026-ajil-china-anti-hegemonism",
      "lit-2025-ajil-unbound-bandung-common-destiny",
      "lit-2021-io-domestic-politics-china-rise-lio",
      "lit-2019-isec-china-world-orders",
      "lit-2017-ris-canary-unga-world-order",
      "lit-2023-ssci-international-law-based-order",
      "lit-2025-pacific-review-transnational-policy-forums",
      "lit-2024-security-studies-collective-logic-hegemonic-order",
      "lit-2026-ia-china-space-order-multiplex",
      "lit-2025-ils-normative-contestation-china",
      "lit-2022-cjcl-approach-international-law",
      "lit-2023-ejil-rao-geping-international-organizations",
      "lit-2024-cjtl-legalization-foreign-relations",
      "lit-2024-cjtl-frl-milestone",
      "lit-2025-jcps-expanding-influence-membership",
      "lit-2024-aplr-varieties-authoritarian-legality",
      "lit-2024-aplr-authoritarian-legality-chinese",
      "lit-2024-cjcl-wrongly-decided-precedents",
      "lit-2023-cjcl-international-rule-law-traditional-culture",
      "lit-2023-cjcl-workplace-sexual-harassment",
      "lit-2023-cjcl-family-education-law",
      "lit-2024-cjtl-frl-political-framing",
      "tt-brookings-2017-international-law-chinese-characteristics",
      "tt-chatham-2024-china-under-siege",
      "tt-brookings-2024-rules-based-order",
      "tt-chatham-2025-competing-visions-china",
      "tt-2025-carnegie-ai-safety-institute",
      "tt-2024-atlantic-council-global-south-chinese-characteristics",
      "tt-2026-carnegie-china-pivot-global-ai",
      "tt-2024-csis-pursuing-global-order",
    ],
  },
  {
    slug: "sovereignty-non-interference",
    title: "Sovereignty and Non-interference",
    eyebrow: "Doctrinal continuity and adaptation",
    dek: "Territorial integrity, non-intervention, human rights, representation, cyber sovereignty, and Taiwan.",
    thesis:
      "Sovereignty remains the most durable organizing principle in China's international legal rhetoric, but its applications now reach far beyond classic territorial disputes into cyberspace, sanctions, human rights, and transnational adjudication.",
    overview: [
      "This topic examines sovereignty as the central organizing concept in China's approach to international law. It covers territorial integrity, non-intervention, representation, human rights scrutiny, cyber sovereignty, national security, and the relationship between domestic constitutional order and external legal claims.",
      "The guide is designed to show both continuity and adaptation. Classic positions on non-interference remain important, but the archive also tracks newer uses of sovereignty in data governance, sanctions responses, foreign state immunity, and disputes over the boundary between legitimate international concern and unlawful intervention.",
    ],
    questions: [
      "How does China distinguish lawful international concern from unlawful interference?",
      "What is the relationship between sovereignty claims and domestic legal instruments?",
      "Where do Taiwan, Hong Kong, Xinjiang, maritime claims, and cyberspace fit within the same doctrinal vocabulary?",
    ],
    featuredIds: [
      "prc-2022-taiwan-question-new-era",
      "prc-2005-anti-secession-law",
      "prc-2017-cyber-cooperation-strategy",
      "intl-1970-friendly-relations",
      "intl-2010-icj-kosovo",
    ],
    readingIds: [
      "lit-chan-sovereignty",
      "lit-kent-1999",
      "lit-foot-2000",
      "lit-burnay-2018",
      "lit-2024-springer-diplomacy-intl-law",
      "lit-2024-ds-one-china-policies-taiwan",
      "lit-2024-jcc-human-rights-world-order",
      "lit-2022-cjcl-approach-international-law",
      "lit-2021-chinesejil-community-shared-future-legalist-turn",
      "lit-2021-cjcl-global-constitutionalism-common-destiny-future-intl-law",
      "lit-2024-njhr-authoritarian-governance-human-rights-china",
      "lit-2025-ajil-unbound-bandung-common-destiny",
      "lit-2025-ia-beyond-liberal-narratives-human-rights-order",
      "lit-2021-io-domestic-politics-china-rise-lio",
      "lit-2017-ris-canary-unga-world-order",
      "lit-2023-ssci-international-law-based-order",
      "lit-2025-jcps-expanding-influence-membership",
      "lit-2024-cjtl-frl-political-framing",
      "lit-2024-cjtl-foreign-state-immunity-dodge",
      "lit-2022-chinesejil-unilateral-sanctions",
      "lit-2025-hague-foreign-related-rule-of-law",
      "lit-2026-aplr-data-export-regime",
      "lit-2026-aplr-return-of-states",
      "lit-2025-iclq-new-doctrine-non-intervention",
      "lit-2025-jhil-china-unbounded-late-qing",
      "lit-2025-cjcl-defamation-greater-china",
      "lit-2025-cjcl-borderline-sovereignty",
      "lit-2025-chinesejil-personal-data-ai",
      "lit-2023-cjcl-international-rule-law-traditional-culture",
      "lit-2023-pacific-review-do-as-i-do",
      "tt-brookings-2017-international-law-chinese-characteristics",
      "tt-2024-atlantic-council-global-south-chinese-characteristics",
      "tt-2024-iiss-gsi-international-policing",
      "tt-2025-carnegie-world-cop-gsi",
      "tt-2026-carnegie-china-pivot-global-ai",
      "tt-lowy-china-rules-based-order",
    ],
  },
  {
    slug: "one-country-two-systems",
    title: "China's One Country, Two Systems: Hong Kong, Macau and Taiwan",
    eyebrow: "Sovereignty, autonomy, and reunification",
    dek: "Basic Laws, reunification policy, Hong Kong and Macau practice, Taiwan white papers, national security, and autonomy.",
    thesis:
      "One country, two systems is both a constitutional arrangement and an international-order argument: it links sovereignty, autonomy, treaty transition, national security, and the PRC's preferred framework for Taiwan reunification.",
    overview: [
      "This topic brings Hong Kong, Macau, and Taiwan into one research frame while preserving the legal differences among them. It covers the Basic Laws, treaty transition, autonomy, national security, reunification policy, Taiwan white papers, and the international implications of one country, two systems.",
      "The value of the topic is comparative. Hong Kong and Macau provide concrete practice under PRC sovereignty, while Taiwan remains framed through reunification and anti-secession law. Together, the materials show how China connects domestic constitutional arrangements with claims about sovereignty, representation, and international legal status.",
    ],
    questions: [
      "How do Hong Kong and Macau practice shape China's claims about sovereignty and autonomy?",
      "How is Taiwan treated differently from Hong Kong and Macau within the same conceptual vocabulary?",
      "What does one country, two systems reveal about the boundary between domestic constitutional law and international legal order?",
    ],
    featuredIds: [
      "prc-1990-basic-law-hk",
      "prc-1993-basic-law-macau",
      "prc-2022-taiwan-question-new-era",
      "practice-2020-hk-national-security-law",
      "prc-2005-anti-secession-law",
    ],
    readingIds: [
      "lit-gittings-2016-hk",
      "lit-chen-2021-hk",
      "lit-lo-2020-macau",
      "lit-chan-sovereignty",
      "lit-2020-hart-hk-national-security-rule-law",
      "lit-2024-ds-one-china-policies-taiwan",
      "lit-2024-springer-diplomacy-intl-law",
      "lit-2025-aplr-hknsl-abuse-fundamental-rights",
      "lit-2025-jufil-attack-taiwan-lawfulness",
      "lit-2026-ajil-taiwan-constitutional-court",
      "lit-2026-ajil-hk-cfa-international-law",
      "lit-2025-cjcl-defamation-greater-china",
      "lit-2024-chinesejil-private-international-law-2023",
      "lit-2024-cjcl-greater-bay-data-flows",
      "lit-2024-upenn-cross-border-insolvency-hk",
      "lit-2022-federal-law-review-hk-nsl",
      "lit-2021-icon-unpalatable-realities",
      "lit-2024-cjtl-foreign-state-immunity-dodge",
      "tt-2024-csis-quarantine-taiwan",
      "tt-2024-csis-taiwan-experts",
      "tt-2024-csis-anti-secession-law-taiwan",
      "tt-2025-hudson-un-resolution-2758",
      "tt-2025-brookings-iomed",
    ],
  },
  {
    slug: "use-of-force",
    title: "China and the Use of Force",
    eyebrow: "Security and restraint",
    dek: "UN Charter law, peacekeeping, intervention, self-defence, non-use of force, and strategic stability.",
    thesis:
      "China's approach to force is built around Charter formalism, Security Council authority, sovereign consent, and suspicion of humanitarian intervention, while its practice has expanded through peacekeeping, anti-piracy operations, and regional security diplomacy.",
    overview: [
      "This topic studies China's approach to the UN Charter rules on force, collective security, consent, self-defence, intervention, peacekeeping, and peaceful settlement. It places formal doctrine alongside actual practice, including Security Council voting, peacekeeping contributions, anti-piracy deployments, and security initiatives.",
      "The guide also highlights areas of tension. China often presents itself as a defender of non-use of force and non-intervention, but Taiwan, maritime disputes, border security, and major-power rivalry require close attention to how legal restraint, deterrence, and sovereignty claims are combined.",
    ],
    questions: [
      "How does China treat Security Council authorization and state consent?",
      "Where has practice expanded beyond older non-intervention rhetoric?",
      "How do Taiwan and maritime disputes complicate China's stated commitment to peaceful settlement?",
    ],
    featuredIds: [
      "intl-1945-un-charter",
      "prc-2023-global-security-initiative",
      "practice-1988-peacekeeping",
      "practice-2008-piracy-escort",
      "practice-2022-ukraine-un-votes",
    ],
    readingIds: [
      "lit-gray-2018",
      "lit-corten-2021",
      "lit-kim-1979",
      "lit-kent-2007-beyond-compliance",
      "lit-2023-book-chinas-law-of-the-sea",
      "lit-2024-cjtl-gsi-legal-lens",
      "lit-2024-jufil-peacetime-maritime-law-enforcement-warships",
      "lit-2025-ejis-mekong-security-development-nexus",
      "lit-2026-ejil-unclos-confrontation",
      "lit-2026-aplr-return-of-states",
      "lit-2025-iclq-new-doctrine-non-intervention",
      "lit-2025-jufil-attack-taiwan-lawfulness",
      "lit-2026-ajil-china-anti-hegemonism",
      "lit-2023-security-studies-illiberal-hegemony",
      "lit-2019-isec-china-world-orders",
      "lit-2024-chinesejil-great-powers-formation",
      "lit-2024-security-studies-collective-logic-hegemonic-order",
      "lit-2026-ia-china-space-order-multiplex",
      "lit-2026-pacific-review-china-partial-space-power",
      "lit-2023-cjip-southeast-asia-order-transition",
      "lit-2017-global-governance-security-council-engagement",
      "lit-2024-jcc-china-russia-reexaminations",
      "lit-2025-harvard-nsj-chinese-lawfare-conflict",
      "lit-2025-upenn-economic-lawfare",
      "lit-2025-chinesejil-maritime-ambitions-bbnj",
      "lit-2025-cjcl-borderline-sovereignty",
      "tt-2024-usip-gsi-takes-shape",
      "tt-2025-usip-police-assistance-global-security",
      "tt-2024-csis-quarantine-taiwan",
      "tt-2024-iiss-gsi-international-policing",
      "tt-2025-carnegie-world-cop-gsi",
      "tt-2025-carnegie-foreign-police-training",
      "tt-brookings-2024-rules-based-order",
      "tt-rusi-2022-global-commons",
      "tt-2024-china-russia-alignment-europe",
    ],
  },
  {
    slug: "global-economic-system",
    title: "China and the Global Economic System",
    eyebrow: "Trade, finance, development",
    dek: "WTO law, IMF surveillance, development cooperation, investment, industrial policy, and economic globalization.",
    thesis:
      "China's economic-order materials combine strong support for multilateral economic institutions with resistance to unilateral pressure and demands for development-sensitive reform of global governance.",
    overview: [
      "This topic covers China's interaction with the institutions and rules of the global economy, including the WTO, IMF, development finance, investment law, industrial policy, debt, supply chains, export controls, and economic globalization. It treats China as both a user of existing rules and a force pressing for institutional change.",
      "The guide helps readers compare China's support for multilateral economic order with its objections to unilateral pressure and unequal rule-making. WTO disputes, Article IV consultations, white papers, BRI finance, and think tank reports together show how legal argument, development policy, and economic statecraft interact.",
    ],
    questions: [
      "How has China used WTO dispute settlement as both respondent and complainant?",
      "When does China defend globalization, and when does it resist existing rules?",
      "How do development finance and industrial policy reshape international economic law debates?",
    ],
    featuredIds: [
      "prc-2001-china-wto-accession",
      "prc-2018-china-wto-whitepaper",
      "wto-ds413",
      "imf-china-article-iv-2024",
      "prc-2021-international-development-cooperation",
    ],
    readingIds: [
      "lit-shaffer-gao-2018",
      "lit-qin-2003",
      "lit-lowenfeld-2008",
      "lit-2024-springer-diplomacy-intl-law",
      "lit-2020-jiel-selective-reshaping",
      "lit-2019-jiel-geoeconomic-order",
      "lit-2025-ripe-status-quo-revisionist-trade-regime",
      "lit-2025-ripe-multilateralism-a-la-carte",
      "lit-2019-ripe-varieties-contestation",
      "lit-2024-wilj-investment-rule-of-law-china",
      "lit-2026-aplr-data-export-regime",
      "lit-2026-aplr-public-participation-cai",
      "lit-2026-aplr-lender-last-resort",
      "lit-2026-aplr-return-of-states",
      "lit-2025-aplr-investment-facilitation",
      "lit-2025-aplr-airline-workforce-rights",
      "lit-2025-tclr-state-role-property-law",
      "lit-2025-tclr-competition-data-protection",
      "lit-2025-tclr-sco-investment-dispute-resolution",
      "lit-2025-tclr-tax-administrative-adjudication",
      "lit-2025-tclr-director-duties-state-invested",
      "lit-2025-upenn-rare-earth-leverage",
      "lit-2025-upenn-international-legal-ordering",
      "lit-2025-upenn-economic-lawfare",
      "lit-2025-chinesejil-personal-data-ai",
      "lit-2025-cjcl-decent-work-bri",
      "lit-2025-cjcl-veil-piercing",
      "lit-2024-cjcl-crypto-assets",
      "lit-2024-cjcl-evergrande-corporate-law",
      "lit-2024-upenn-liquidated-damages",
      "lit-2024-cjcl-long-short-videos",
      "lit-2023-upenn-ip-legislation-holism",
      "lit-2022-jwt-special-economic-zones-order",
      "lit-2024-china-information-standards-ground-up",
      "lit-2023-ia-china-liberal-order",
      "lit-2021-io-domestic-politics-china-rise-lio",
      "lit-2019-isec-china-world-orders",
      "lit-2025-jogss-china-russia-sanctions-implementation",
      "lit-2025-wq-old-logic-economic-weapons",
      "lit-2025-pacific-review-transnational-policy-forums",
      "lit-2026-ia-ai-tech-transfer-global-south",
      "lit-2024-area-dev-policy-china-economic-multipolar",
      "tt-2024-carnegie-global-economic-governance",
      "tt-2024-merics-guerrilla-global-economy",
      "tt-brookings-2024-rules-based-order",
      "tt-chatham-2025-competing-visions-china",
      "tt-2025-carnegie-ai-safety-institute",
      "tt-2024-atlantic-council-global-south-chinese-characteristics",
      "tt-2024-atlantic-council-tech-competition-global-south",
      "tt-2026-carnegie-china-pivot-global-ai",
      "tt-aiddata-2023-bri-reboot",
    ],
  },
  {
    slug: "sanctions-anti-sanctions",
    title: "Sanctions and Anti-sanctions",
    eyebrow: "Economic security law",
    dek: "Countermeasures, blocking rules, export controls, foreign sanctions, extraterritoriality, and economic coercion.",
    thesis:
      "China's anti-sanctions lawmaking translates objections to unilateral coercion and extraterritorial jurisdiction into domestic legal tools, creating a bridge between sovereignty discourse and economic security governance.",
    overview: [
      "This topic focuses on sanctions, counter-sanctions, blocking rules, export controls, long-arm jurisdiction, unreliable entity mechanisms, and economic coercion. It connects China's international law objections to unilateral sanctions with the domestic legal instruments used to resist or retaliate against foreign measures.",
      "The archive is organized to show sanctions as both doctrine and practice. Readers can trace how China frames sanctions as sovereignty violations, how it builds countermeasures into domestic law, and how firms, courts, regulators, and foreign governments are drawn into conflicts over extraterritoriality.",
    ],
    questions: [
      "Which foreign measures are framed as unlawful sanctions or interference?",
      "How do blocking rules, export controls, and counter-sanctions interact?",
      "Does anti-sanctions law operate as international law argument, domestic regulatory tool, or both?",
    ],
    featuredIds: [
      "prc-2021-anti-foreign-sanctions-law",
      "prc-2021-blocking-rules",
      "prc-2020-export-control-law",
      "practice-2021-sanctions-countermeasures",
      "prc-2019-china-us-trade-consultations",
    ],
    readingIds: [
      "lit-roberts-moraes-ferguson-2019",
      "bib-tt-merics-2023-decoupling",
      "lit-2024-cjtl-blocking-statutes",
      "lit-2024-ssrn-us-china-sanctions-war",
      "lit-2022-chinesejil-unilateral-sanctions",
      "lit-2025-jogss-china-russia-sanctions-implementation",
      "lit-2025-wq-old-logic-economic-weapons",
      "lit-2025-chinesejil-sanctions-human-rights-due-diligence",
      "lit-2024-yjil-economic-coercion",
      "lit-2025-cpsr-china-two-tiered-sanctions",
      "lit-2023-orbis-foreign-related-rule-law",
      "lit-2025-hague-foreign-related-rule-of-law",
      "lit-2026-aplr-data-export-regime",
      "lit-2026-aplr-return-of-states",
      "lit-2025-upenn-rare-earth-leverage",
      "lit-2025-upenn-economic-lawfare",
      "tt-chatham-2024-china-under-siege",
      "tt-merics-2021-afsl-warning",
      "tt-merics-2024-how-china-imposes-sanctions",
      "tt-2024-montaigne-china-extraterritoriality",
      "tt-2024-ep-eu-china-derisking",
    ],
  },
  {
    slug: "belt-and-road",
    title: "Belt and Road Initiative",
    eyebrow: "Parallel order or connective tissue?",
    dek: "Infrastructure, development finance, legal connectivity, dispute settlement, and the community of shared future.",
    thesis:
      "BRI should be studied as a legal and institutional practice rather than only an infrastructure brand: it links development finance, standards, dispute resolution, soft law, and diplomatic ordering.",
    overview: [
      "This topic treats the Belt and Road Initiative as a legal and institutional phenomenon, not only as an infrastructure programme. It covers policy documents, development finance, standards, debt, environmental and social governance, connectivity agreements, dispute settlement, and the idea of a community of shared future.",
      "The central question is whether BRI builds a parallel order, supports existing institutions, or does both in different contexts. The guide brings together official documents, project practice, research reports, and dispute materials to examine how infrastructure diplomacy can produce legal effects without a single founding treaty.",
    ],
    questions: [
      "Does BRI build a parallel order, supplement existing institutions, or do both in different settings?",
      "What legal instruments and forums make BRI durable?",
      "How do development, debt, infrastructure, and dispute settlement interact?",
    ],
    featuredIds: [
      "prc-2015-bri-vision-actions",
      "prc-2023-bri-whitepaper",
      "practice-2015-aiib-articles",
      "practice-2023-bri-forum-third",
      "tt-csis-bri-reconnecting",
    ],
    readingIds: [
      "lit-brautigam-2009",
      "lit-rudolf-2021",
      "lit-wang-jiangyu-bri",
      "lit-hughes-bri-law",
      "lit-erie-2021-chinese-law-development",
      "lit-2025-fudan-environmental-diplomacy-bri",
      "lit-2026-ripe-institutional-layering-gdi",
      "lit-2025-ajls-china-modernization-bri-legal-pluralism",
      "lit-2025-ajls-bri-not-novel-law-making",
      "lit-2025-aplr-investment-facilitation",
      "lit-2025-tclr-sco-investment-dispute-resolution",
      "lit-2025-cjcl-decent-work-bri",
      "lit-2023-ajil-geoeconomics-bri-disputes",
      "lit-2020-jiel-selective-reshaping",
      "lit-2024-china-information-standards-ground-up",
      "lit-2023-pacific-review-do-as-i-do",
      "lit-2025-pacific-review-transnational-policy-forums",
      "lit-2026-ia-ai-tech-transfer-global-south",
      "lit-2024-area-dev-policy-china-economic-multipolar",
      "lit-2026-ia-china-space-order-multiplex",
      "tt-2024-atlantic-council-global-south-chinese-characteristics",
      "tt-2024-atlantic-council-tech-competition-global-south",
      "tt-aiddata-2021-banking-bri",
      "tt-aiddata-2023-bri-reboot",
      "tt-csis-2015-xi-bri",
      "tt-csis-2018-bri-holes",
      "tt-csis-chinapower-bri",
      "tt-csis-maritime-silk-road",
    ],
  },
  {
    slug: "dispute-settlement",
    title: "Dispute Settlement",
    eyebrow: "From international to China-centred transnational approaches",
    dek: "WTO litigation, ICJ participation, arbitration, mediation, Chinese courts, and forum design.",
    thesis:
      "China's dispute-settlement practice is not simply pro- or anti-adjudication. It is forum-specific: active in WTO litigation, cautious toward compulsory maritime adjudication, increasingly interested in mediation, and attentive to China-centred transnational mechanisms.",
    overview: [
      "This topic maps China's use of, resistance to, and redesign of international dispute settlement. It includes WTO litigation, ICJ advisory proceedings, arbitration, maritime disputes, mediation, commercial courts, foreign state immunity, enforcement, and the International Organization for Mediation.",
      "The guide avoids a simple pro-court or anti-court label. China is highly active in some rule-based forums, deeply resistant to others, and increasingly interested in mechanisms that are transnational but more China-centred. The topic therefore follows consent, jurisdiction, enforcement, and forum design across different legal settings.",
    ],
    questions: [
      "Which forums does China use, resist, or try to reshape?",
      "How do consent, jurisdiction, sovereignty, and enforcement appear across disputes?",
      "What would a China-centred transnational dispute settlement model look like?",
    ],
    featuredIds: [
      "prc-2016-south-china-sea-position",
      "intl-2016-scs-award",
      "wto-ds413",
      "practice-2023-saudi-iran",
      "intl-2024-icj-climate",
    ],
    readingIds: [
      "lit-cai-2019",
      "lit-shaffer-gao-2018",
      "lit-ginsburg-2019",
      "lit-potter-2011",
      "lit-2024-cambridge-handbook-china-intl-law",
      "lit-2020-hart-hk-national-security-rule-law",
      "lit-2024-cjtl-cicc-global-context",
      "lit-2024-wilj-investment-rule-of-law-china",
      "lit-2023-ajil-geoeconomics-bri-disputes",
      "lit-2023-ssci-international-law-based-order",
      "lit-2025-pkulj-cicc-cross-border-mechanism",
      "lit-2025-tclr-sco-investment-dispute-resolution",
      "lit-2025-tclr-foreign-related-civil-procedure",
      "lit-2025-tclr-annulment-arbitral-awards",
      "lit-2025-upenn-party-court-fifth-reform",
      "lit-2025-columbia-moralizing-courts",
      "lit-2025-chinesejil-practice-public-international-law-2022",
      "lit-2025-tclr-tax-administrative-adjudication",
      "lit-2025-cjcl-veil-piercing",
      "lit-2026-ejil-unclos-confrontation",
      "lit-2026-aplr-public-participation-cai",
      "lit-2026-ajil-hk-cfa-international-law",
      "lit-2024-chinesejil-great-powers-formation",
      "lit-2024-chinesejil-private-international-law-2023",
      "lit-2024-jpil-cicc-jurisdiction",
      "lit-2024-aplr-cicc-performance",
      "lit-2024-jids-new-international-commercial-courts",
      "lit-2024-cjcl-evergrande-corporate-law",
      "lit-2024-cjcl-wrongly-decided-precedents",
      "lit-2024-upenn-cross-border-insolvency-hk",
      "lit-2024-upenn-liquidated-damages",
      "lit-2024-aplr-varieties-authoritarian-legality",
      "lit-2024-aplr-authoritarian-legality-chinese",
      "lit-2023-cjcl-forum-non-conveniens",
      "lit-2024-cjcl-long-short-videos",
      "lit-2023-cjcl-wrongful-death-awards",
      "lit-2023-ejil-rao-geping-international-organizations",
      "lit-2024-cjtl-foreign-state-immunity-dodge",
      "lit-2026-ajil-taiwan-constitutional-court",
      "tt-2024-csis-quarantine-taiwan",
      "tt-chatham-2017-dispute-settlement",
      "tt-2025-brookings-iomed",
      "tt-2025-austchina-iomed",
    ],
  },
];

export function getGuide(slug) {
  return guides.find((guide) => guide.slug === slug);
}
