import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { toCsv } from "../src/lib/csv.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = join(root, "src/data");

const recordsHeaders = [
  "id",
  "title_en",
  "title_zh",
  "source_type",
  "institution",
  "date",
  "topics",
  "jurisdiction",
  "language",
  "url",
  "doi_or_isbn",
  "citation",
  "summary",
  "significance_note",
];

const timelineHeaders = [
  "id",
  "date",
  "title",
  "topics",
  "record_ids",
  "summary",
];

const bibliographyHeaders = [
  "id",
  "title",
  "author",
  "date",
  "type",
  "topics",
  "url",
  "citation",
  "note",
];

function portalUrl(query) {
  return `https://www.google.com/search?q=${encodeURIComponent(query)}`;
}

function wtoCaseUrl(ds) {
  return `https://www.wto.org/english/tratop_e/dispu_e/cases_e/ds${ds}_e.htm`;
}

function worldcatUrl(query) {
  return `https://search.worldcat.org/search?q=${encodeURIComponent(query)}`;
}

function record({
  id,
  title,
  titleZh = "",
  sourceType,
  institution,
  date,
  topics,
  jurisdiction,
  language = "English",
  url,
  doi = "",
  citation,
  summary,
  note,
}) {
  return {
    id,
    title_en: title,
    title_zh: titleZh,
    source_type: sourceType,
    institution,
    date,
    topics: Array.isArray(topics) ? topics.join(";") : topics,
    jurisdiction,
    language,
    url,
    doi_or_isbn: doi,
    citation,
    summary,
    significance_note: note,
  };
}

const officialRecords = [
  record({
    id: "prc-1982-constitution",
    title: "Constitution of the People's Republic of China",
    titleZh: "中华人民共和国宪法",
    sourceType: "PRC official document",
    institution: "National People's Congress",
    date: "1982-12-04",
    topics: ["theory-order", "sovereignty-non-interference"],
    jurisdiction: "China",
    url: "http://www.npc.gov.cn/englishnpc/constitution2019/constitution.shtml",
    citation: "Constitution of the People's Republic of China (adopted 4 December 1982, as amended).",
    summary: "The constitutional baseline for PRC state institutions, sovereignty, and foreign relations authority.",
    note: "Useful for connecting China's external legal positions to domestic constitutional structure.",
  }),
  record({
    id: "prc-1990-basic-law-hk",
    title: "Basic Law of the Hong Kong Special Administrative Region",
    titleZh: "中华人民共和国香港特别行政区基本法",
    sourceType: "PRC official document",
    institution: "National People's Congress",
    date: "1990-04-04",
    topics: ["sovereignty-non-interference", "dispute-settlement"],
    jurisdiction: "Hong Kong SAR",
    url: "https://www.basiclaw.gov.hk/en/basiclaw/index.html",
    citation: "Basic Law of the Hong Kong Special Administrative Region (adopted 4 April 1990).",
    summary: "Constitutional instrument for Hong Kong's post-1997 legal order under Chinese sovereignty.",
    note: "Central for debates over sovereignty, autonomy, treaty continuity, and judicial authority.",
  }),
  record({
    id: "prc-1993-whitepaper-taiwan",
    title: "The Taiwan Question and Reunification of China",
    titleZh: "台湾问题与中国的统一",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "1993-08-31",
    topics: ["sovereignty-non-interference", "theory-order"],
    jurisdiction: "China",
    url: "https://www.google.com/search?q=The+Taiwan+Question+and+Reunification+of+China+1993+State+Council+Information+Office",
    citation: "State Council Information Office, 'The Taiwan Question and Reunification of China' (31 August 1993).",
    summary: "Early PRC white paper setting out the official position on Taiwan and sovereignty.",
    note: "A baseline text for tracking continuity and change in PRC sovereignty doctrine.",
  }),
  record({
    id: "prc-2001-china-wto-accession",
    title: "Protocol on the Accession of the People's Republic of China",
    titleZh: "中华人民共和国加入世界贸易组织议定书",
    sourceType: "PRC official document",
    institution: "World Trade Organization",
    date: "2001-11-10",
    topics: ["global-economic-system", "dispute-settlement"],
    jurisdiction: "International",
    url: "https://docs.wto.org/dol2fe/Pages/SS/directdoc.aspx?filename=q:/WT/L/432.pdf",
    citation: "WTO, 'Protocol on the Accession of the People's Republic of China' WT/L/432 (10 November 2001).",
    summary: "The legal instrument by which China acceded to the WTO.",
    note: "Foundational for studying China's integration into the trade law system and subsequent disputes.",
  }),
  record({
    id: "prc-2005-anti-secession-law",
    title: "Anti-Secession Law",
    titleZh: "反分裂国家法",
    sourceType: "PRC official document",
    institution: "National People's Congress",
    date: "2005-03-14",
    topics: ["sovereignty-non-interference", "use-of-force"],
    jurisdiction: "China",
    url: "http://www.npc.gov.cn/zgrdw/englishnpc/Law/2007-12/13/content_1384099.htm",
    citation: "Anti-Secession Law of the People's Republic of China (adopted 14 March 2005).",
    summary: "PRC legislation concerning Taiwan, peaceful reunification, and conditions for non-peaceful means.",
    note: "Key text for linking sovereignty claims with PRC positions on force and domestic legal authorization.",
  }),
  record({
    id: "prc-2011-peaceful-development",
    title: "China's Peaceful Development",
    titleZh: "中国的和平发展",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2011-09-06",
    topics: ["theory-order", "use-of-force", "global-economic-system"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/white_paper/2014/09/09/content_281474986284646.htm",
    citation: "State Council Information Office, 'China's Peaceful Development' (6 September 2011).",
    summary: "White paper presenting peaceful development as a guiding framework for China's rise.",
    note: "Important for assessing how official discourse links development, security, and international order.",
  }),
  record({
    id: "prc-2011-foreign-aid",
    title: "China's Foreign Aid",
    titleZh: "中国的对外援助",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2011-04-21",
    topics: ["global-economic-system", "belt-and-road"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/white_paper/2014/09/09/content_281474986284620.htm",
    citation: "State Council Information Office, 'China's Foreign Aid' (21 April 2011).",
    summary: "White paper describing principles and modes of Chinese foreign aid.",
    note: "A pre-BRI reference point for Chinese development cooperation norms.",
  }),
  record({
    id: "prc-2012-diaoyu-whitepaper",
    title: "Diaoyu Dao, an Inherent Territory of China",
    titleZh: "钓鱼岛是中国的固有领土",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2012-09-25",
    topics: ["sovereignty-non-interference", "use-of-force"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/white_paper/2014/08/23/content_281474982986592.htm",
    citation: "State Council Information Office, 'Diaoyu Dao, an Inherent Territory of China' (25 September 2012).",
    summary: "Official white paper setting out China's claim to Diaoyu Dao/Senkaku Islands.",
    note: "Useful for comparison with maritime and territorial sovereignty arguments elsewhere.",
  }),
  record({
    id: "prc-2014-foreign-aid",
    title: "China's Foreign Aid (2014)",
    titleZh: "中国的对外援助（2014）",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2014-07-10",
    topics: ["global-economic-system", "belt-and-road"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/white_paper/2014/08/23/content_281474982986592.htm",
    citation: "State Council Information Office, 'China's Foreign Aid (2014)' (10 July 2014).",
    summary: "Follow-up white paper on China's foreign aid policies and practices.",
    note: "Helps track development-cooperation language before the BRI white papers.",
  }),
  record({
    id: "prc-2015-bri-vision-actions",
    title: "Vision and Actions on Jointly Building Silk Road Economic Belt and 21st-Century Maritime Silk Road",
    titleZh: "推动共建丝绸之路经济带和21世纪海上丝绸之路的愿景与行动",
    sourceType: "PRC official document",
    institution: "National Development and Reform Commission",
    date: "2015-03-28",
    topics: ["belt-and-road", "global-economic-system", "theory-order"],
    jurisdiction: "China",
    url: "https://en.ndrc.gov.cn/news/pressreleases/202104/t20210429_1279338.html",
    citation: "NDRC, MFA and MOFCOM, 'Vision and Actions on Jointly Building Silk Road Economic Belt and 21st-Century Maritime Silk Road' (28 March 2015).",
    summary: "Foundational policy document for the Belt and Road Initiative.",
    note: "Frames BRI as connectivity, cooperation, and development rather than treaty-based institutional integration.",
  }),
  record({
    id: "prc-2016-south-china-sea-position",
    title: "Position Paper on the Matter of Jurisdiction in the South China Sea Arbitration",
    titleZh: "关于菲律宾所提南海仲裁案管辖权问题的立场文件",
    sourceType: "PRC official document",
    institution: "Ministry of Foreign Affairs",
    date: "2014-12-07",
    topics: ["sovereignty-non-interference", "dispute-settlement"],
    jurisdiction: "China",
    url: "https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/2649_665393/201412/t20141207_679387.html",
    citation: "Ministry of Foreign Affairs, 'Position Paper on the Matter of Jurisdiction in the South China Sea Arbitration' (7 December 2014).",
    summary: "PRC position rejecting jurisdiction in the arbitration initiated by the Philippines.",
    note: "Central text for China's consent-based approach to international adjudication in maritime disputes.",
  }),
  record({
    id: "prc-2016-scs-whitepaper",
    title: "China Adheres to the Position of Settling Through Negotiation the Relevant Disputes Between China and the Philippines in the South China Sea",
    titleZh: "中国坚持通过谈判解决中国与菲律宾在南海的有关争议",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2016-07-13",
    topics: ["sovereignty-non-interference", "dispute-settlement"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/white_paper/2016/07/13/content_281475392503075.htm",
    citation: "State Council Information Office, 'China Adheres to the Position of Settling Through Negotiation...' (13 July 2016).",
    summary: "Official white paper after the South China Sea arbitral award.",
    note: "Shows China's preference for negotiation and objections to compulsory arbitration in the dispute.",
  }),
  record({
    id: "prc-2017-xis-davos-speech",
    title: "Jointly Shoulder Responsibility of Our Times, Promote Global Growth",
    titleZh: "共担时代责任 共促全球发展",
    sourceType: "PRC official document",
    institution: "World Economic Forum / Xinhua",
    date: "2017-01-17",
    topics: ["theory-order", "global-economic-system"],
    jurisdiction: "China",
    url: "https://www.xinhuanet.com/english/2017-01/18/c_135993184.htm",
    citation: "Xi Jinping, 'Jointly Shoulder Responsibility of Our Times, Promote Global Growth' (Davos, 17 January 2017).",
    summary: "Speech defending economic globalization and multilateral cooperation.",
    note: "Important for the official narrative of China as a supporter of globalization.",
  }),
  record({
    id: "prc-2017-cyber-cooperation-strategy",
    title: "International Strategy of Cooperation on Cyberspace",
    titleZh: "网络空间国际合作战略",
    sourceType: "PRC official document",
    institution: "Ministry of Foreign Affairs",
    date: "2017-03-01",
    topics: ["theory-order", "sovereignty-non-interference"],
    jurisdiction: "China",
    url: "https://www.fmprc.gov.cn/mfa_eng/wjdt_665385/2649_665393/201703/t20170301_679554.html",
    citation: "Ministry of Foreign Affairs, 'International Strategy of Cooperation on Cyberspace' (1 March 2017).",
    summary: "Policy document advancing cyber sovereignty and international cooperation.",
    note: "Useful for studying the extension of sovereignty discourse into digital governance.",
  }),
  record({
    id: "prc-2018-china-wto-whitepaper",
    title: "China and the World Trade Organization",
    titleZh: "中国与世界贸易组织",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2018-06-28",
    topics: ["global-economic-system", "dispute-settlement"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/white_paper/2018/06/28/content_281476201898696.htm",
    citation: "State Council Information Office, 'China and the World Trade Organization' (28 June 2018).",
    summary: "White paper defending China's record in WTO accession and implementation.",
    note: "Key source for China's self-presentation as a WTO participant and reform stakeholder.",
  }),
  record({
    id: "prc-2019-china-us-trade-consultations",
    title: "China's Position on the China-US Economic and Trade Consultations",
    titleZh: "关于中美经贸磋商的中方立场",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2019-06-02",
    topics: ["global-economic-system", "sanctions-anti-sanctions"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/whitepaper/201906/02/content_WS5cf36f5bc6d0a46e8bb41191.html",
    citation: "State Council Information Office, 'China's Position on the China-US Economic and Trade Consultations' (2 June 2019).",
    summary: "White paper on the US-China trade conflict and negotiations.",
    note: "Connects trade law, unilateral measures, and China's rhetoric of mutual respect.",
  }),
  record({
    id: "prc-2020-export-control-law",
    title: "Export Control Law of the People's Republic of China",
    titleZh: "中华人民共和国出口管制法",
    sourceType: "PRC official document",
    institution: "National People's Congress",
    date: "2020-10-17",
    topics: ["sanctions-anti-sanctions", "global-economic-system"],
    jurisdiction: "China",
    url: "https://www.google.com/search?q=Export+Control+Law+of+the+People%27s+Republic+of+China+2020+NPC+English",
    citation: "Export Control Law of the People's Republic of China (adopted 17 October 2020).",
    summary: "Framework law for export controls and related national security measures.",
    note: "Part of the legal architecture for economic security and countermeasure capacity.",
  }),
  record({
    id: "prc-2021-blocking-rules",
    title: "Rules on Counteracting Unjustified Extra-territorial Application of Foreign Legislation and Other Measures",
    titleZh: "阻断外国法律与措施不当域外适用办法",
    sourceType: "PRC official document",
    institution: "Ministry of Commerce",
    date: "2021-01-09",
    topics: ["sanctions-anti-sanctions", "global-economic-system"],
    jurisdiction: "China",
    url: "https://english.mofcom.gov.cn/Policies/GeneralPolicies/art/2021/art_98677d0ed28b41b9adeff27b00c9d001.html",
    citation: "MOFCOM, 'Rules on Counteracting Unjustified Extra-territorial Application of Foreign Legislation and Other Measures' (9 January 2021).",
    summary: "Chinese blocking rules responding to foreign extraterritorial measures.",
    note: "Core source for China's legal response to sanctions and extraterritorial jurisdiction.",
  }),
  record({
    id: "prc-2021-anti-foreign-sanctions-law",
    title: "Anti-Foreign Sanctions Law of the People's Republic of China",
    titleZh: "中华人民共和国反外国制裁法",
    sourceType: "PRC official document",
    institution: "National People's Congress",
    date: "2021-06-10",
    topics: ["sanctions-anti-sanctions", "sovereignty-non-interference"],
    jurisdiction: "China",
    url: "https://www.google.com/search?q=Anti-Foreign+Sanctions+Law+of+the+People%27s+Republic+of+China+English+NPC",
    citation: "Anti-Foreign Sanctions Law of the People's Republic of China (adopted 10 June 2021).",
    summary: "National law authorizing countermeasures against foreign sanctions.",
    note: "Essential for studying how China domesticates responses to unilateral sanctions.",
  }),
  record({
    id: "prc-2021-international-development-cooperation",
    title: "China's International Development Cooperation in the New Era",
    titleZh: "新时代的中国国际发展合作",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2021-01-10",
    topics: ["belt-and-road", "global-economic-system"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/whitepaper/202101/10/content_WS5ffa6bbbc6d0f72576943922.html",
    citation: "State Council Information Office, 'China's International Development Cooperation in the New Era' (10 January 2021).",
    summary: "White paper on China's development cooperation principles and practices.",
    note: "Links BRI, South-South cooperation, and development governance.",
  }),
  record({
    id: "prc-2022-taiwan-question-new-era",
    title: "The Taiwan Question and China's Reunification in the New Era",
    titleZh: "台湾问题与新时代中国统一事业",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2022-08-10",
    topics: ["sovereignty-non-interference", "use-of-force"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/whitepaper/202208/10/content_WS62f34f46c6d02e533532f0ac.html",
    citation: "State Council Information Office, 'The Taiwan Question and China's Reunification in the New Era' (10 August 2022).",
    summary: "Recent PRC white paper on Taiwan policy and reunification.",
    note: "Shows updated official framing of sovereignty, national rejuvenation, and peaceful reunification.",
  }),
  record({
    id: "prc-2023-global-security-initiative",
    title: "The Global Security Initiative Concept Paper",
    titleZh: "全球安全倡议概念文件",
    sourceType: "PRC official document",
    institution: "Ministry of Foreign Affairs",
    date: "2023-02-21",
    topics: ["theory-order", "use-of-force", "sovereignty-non-interference"],
    jurisdiction: "China",
    url: "https://www.mfa.gov.cn/eng/wjbxw/202302/t20230221_11028348.html",
    citation: "Ministry of Foreign Affairs, 'The Global Security Initiative Concept Paper' (21 February 2023).",
    summary: "Concept paper elaborating China's Global Security Initiative.",
    note: "Frames security governance through indivisible security, sovereignty, and opposition to bloc confrontation.",
  }),
  record({
    id: "prc-2023-global-community-shared-future",
    title: "A Global Community of Shared Future: China's Proposals and Actions",
    titleZh: "携手构建人类命运共同体：中国的倡议与行动",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2023-09-26",
    topics: ["theory-order", "global-economic-system", "belt-and-road"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/whitepaper/202309/26/content_WS6512703ac6d0868f4e8dfc37.html",
    citation: "State Council Information Office, 'A Global Community of Shared Future: China's Proposals and Actions' (26 September 2023).",
    summary: "White paper presenting the community of shared future as a broad international-order concept.",
    note: "A key official statement of China's normative vocabulary for global governance.",
  }),
  record({
    id: "prc-2023-bri-whitepaper",
    title: "The Belt and Road Initiative: A Key Pillar of the Global Community of Shared Future",
    titleZh: "共建“一带一路”：构建人类命运共同体的重大实践",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2023-10-10",
    topics: ["belt-and-road", "global-economic-system", "theory-order"],
    jurisdiction: "China",
    url: "https://english.www.gov.cn/archive/whitepaper/202310/10/content_WS6524b55fc6d0868f4e8e014c.html",
    citation: "State Council Information Office, 'The Belt and Road Initiative: A Key Pillar of the Global Community of Shared Future' (10 October 2023).",
    summary: "White paper on BRI principles, achievements, and global-order significance.",
    note: "Central source for evaluating whether BRI is presented as a parallel or complementary order.",
  }),
  record({
    id: "prc-2023-global-governance-reform",
    title: "Proposal of the People's Republic of China on the Reform and Development of Global Governance",
    titleZh: "关于全球治理改革和建设的中国方案",
    sourceType: "PRC official document",
    institution: "Ministry of Foreign Affairs",
    date: "2023-09-13",
    topics: ["theory-order", "global-economic-system", "use-of-force"],
    jurisdiction: "China",
    url: "https://www.mfa.gov.cn/eng/zy/gb/202405/t20240531_11367498.html",
    citation: "Ministry of Foreign Affairs, 'Proposal of the People's Republic of China on the Reform and Development of Global Governance' (13 September 2023).",
    summary: "MFA proposal on global governance reform across security, development, human rights, and institutions.",
    note: "Useful as a compact statement of China's reformist rather than withdrawalist posture.",
  }),
  record({
    id: "prc-2023-gdi-progress-report",
    title: "Global Development Initiative Progress Report",
    sourceType: "PRC official document",
    institution: "Center for International Knowledge on Development",
    date: "2023-06-20",
    topics: ["global-economic-system", "belt-and-road"],
    jurisdiction: "China",
    url: "https://www.google.com/search?q=Global+Development+Initiative+Progress+Report+2023+China",
    citation: "Center for International Knowledge on Development, 'Global Development Initiative Progress Report' (2023).",
    summary: "Report on implementation of the Global Development Initiative.",
    note: "Connects Chinese development discourse with institutional and project-based cooperation.",
  }),
  record({
    id: "prc-2024-punitive-measures-taiwan",
    title: "Guidelines on Punishing Taiwan Independence Diehards for Splitting the Country and Inciting Secession",
    titleZh: "关于依法惩治“台独”顽固分子分裂国家、煽动分裂国家犯罪的意见",
    sourceType: "PRC official document",
    institution: "Supreme People's Court and related authorities",
    date: "2024-06-21",
    topics: ["sovereignty-non-interference", "dispute-settlement"],
    jurisdiction: "China",
    url: "https://www.google.com/search?q=Guidelines+Punishing+Taiwan+Independence+Diehards+2024+China+English",
    citation: "SPC, SPP, Ministry of Public Security, Ministry of State Security and Ministry of Justice, 'Guidelines on Punishing Taiwan Independence Diehards...' (21 June 2024).",
    summary: "Guidelines on criminal liability relating to Taiwan independence activities.",
    note: "Illustrates the domestic legal extension of sovereignty claims.",
  }),
];

const internationalRecords = [
  ["intl-1945-un-charter", "Charter of the United Nations", "United Nations", "1945-06-26", "use-of-force;sovereignty-non-interference;theory-order", "https://www.un.org/en/about-us/un-charter", "International law document", "International", "UN Charter (signed 26 June 1945, entered into force 24 October 1945).", "Foundational treaty for sovereignty, non-use of force, and collective security.", "Baseline text for comparing China's doctrine with the post-1945 legal order."],
  ["intl-1970-friendly-relations", "Declaration on Principles of International Law concerning Friendly Relations and Co-operation among States", "United Nations General Assembly", "1970-10-24", "sovereignty-non-interference;use-of-force;theory-order", "https://digitallibrary.un.org/record/202170", "International law document", "International", "UNGA Res 2625 (XXV) (24 October 1970).", "Canonical General Assembly declaration on sovereign equality, non-intervention, and force.", "Frequently invoked in debates over China's doctrinal commitments."],
  ["intl-1971-unga-2758", "Restoration of the lawful rights of the People's Republic of China in the United Nations", "United Nations General Assembly", "1971-10-25", "sovereignty-non-interference;theory-order", "https://digitallibrary.un.org/record/192054", "International law document", "International", "UNGA Res 2758 (XXVI) (25 October 1971).", "Resolution seating the PRC at the United Nations.", "Key legal-political reference in PRC arguments about representation and Taiwan."],
  ["intl-1982-unclos", "United Nations Convention on the Law of the Sea", "United Nations", "1982-12-10", "sovereignty-non-interference;dispute-settlement", "https://www.un.org/depts/los/convention_agreements/texts/unclos/unclos_e.pdf", "International law document", "International", "United Nations Convention on the Law of the Sea (opened for signature 10 December 1982).", "Comprehensive treaty governing maritime zones and dispute settlement.", "Necessary context for the South China Sea arbitration and maritime sovereignty disputes."],
  ["intl-1994-wto-agreement", "Marrakesh Agreement Establishing the World Trade Organization", "World Trade Organization", "1994-04-15", "global-economic-system;dispute-settlement", "https://www.wto.org/english/docs_e/legal_e/04-wto_e.htm", "International law document", "International", "Marrakesh Agreement Establishing the World Trade Organization (15 April 1994).", "Treaty establishing the WTO and its dispute settlement system.", "Core institutional frame for China's trade-law practice after accession."],
  ["intl-1996-icj-nuclear-weapons", "Legality of the Threat or Use of Nuclear Weapons Advisory Opinion", "International Court of Justice", "1996-07-08", "use-of-force;theory-order", "https://www.icj-cij.org/case/95", "International law document", "International", "Legality of the Threat or Use of Nuclear Weapons, Advisory Opinion, ICJ Reports 1996.", "ICJ advisory opinion on nuclear weapons and the law of force.", "Useful for comparing Chinese positions on strategic stability and Charter restraints."],
  ["intl-2004-icj-wall", "Legal Consequences of the Construction of a Wall in the Occupied Palestinian Territory", "International Court of Justice", "2004-07-09", "use-of-force;sovereignty-non-interference", "https://www.icj-cij.org/case/131", "International law document", "International", "Legal Consequences of the Construction of a Wall, Advisory Opinion, ICJ Reports 2004.", "ICJ advisory opinion addressing occupation, self-determination, and use of force.", "Relevant to China's voting and rhetorical practice on occupied territories."],
  ["intl-2010-icj-kosovo", "Accordance with International Law of the Unilateral Declaration of Independence in Respect of Kosovo", "International Court of Justice", "2010-07-22", "sovereignty-non-interference;dispute-settlement", "https://www.icj-cij.org/case/141", "International law document", "International", "Accordance with International Law of the Unilateral Declaration of Independence in Respect of Kosovo, Advisory Opinion, ICJ Reports 2010.", "ICJ advisory opinion on unilateral declarations of independence.", "Useful comparison point for PRC positions on territorial integrity and secession."],
  ["intl-2015-paris-agreement", "Paris Agreement", "United Nations Framework Convention on Climate Change", "2015-12-12", "global-economic-system;theory-order", "https://unfccc.int/process-and-meetings/the-paris-agreement/the-paris-agreement", "International law document", "International", "Paris Agreement (adopted 12 December 2015, entered into force 4 November 2016).", "Climate treaty reflecting nationally determined contributions and differentiated responsibilities.", "Shows a governance model where China emphasizes equity, development, and multilateralism."],
  ["intl-2016-scs-award", "South China Sea Arbitration Award", "Permanent Court of Arbitration", "2016-07-12", "sovereignty-non-interference;dispute-settlement", "https://pca-cpa.org/en/cases/7/", "International law document", "International", "South China Sea Arbitration (Philippines v China), Award (12 July 2016).", "UNCLOS Annex VII award in the Philippines-China arbitration.", "A central reference for China's rejection of compulsory adjudication in a major maritime dispute."],
  ["intl-2019-icj-chagos", "Legal Consequences of the Separation of the Chagos Archipelago from Mauritius in 1965", "International Court of Justice", "2019-02-25", "sovereignty-non-interference;theory-order", "https://www.icj-cij.org/case/169", "International law document", "International", "Legal Consequences of the Separation of the Chagos Archipelago, Advisory Opinion, ICJ Reports 2019.", "ICJ advisory opinion on decolonization and territorial integrity.", "Useful for tracking China's positions on colonial history and self-determination."],
  ["intl-2024-icj-climate", "Obligations of States in Respect of Climate Change", "International Court of Justice", "2024-03-22", "global-economic-system;theory-order;dispute-settlement", "https://www.icj-cij.org/case/187", "International law document", "International", "Obligations of States in Respect of Climate Change, ICJ advisory proceedings.", "Advisory proceedings on climate obligations under international law.", "A live site for China's legal arguments about development, responsibility, and multilateral treaty regimes."],
].map(([id, title, institution, date, topics, url, sourceType, jurisdiction, citation, summary, note]) =>
  record({ id, title, sourceType, institution, date, topics, jurisdiction, url, citation, summary, note }),
);

const statePractice = [
  ["practice-1971-prc-un-seat", "PRC assumes China's seat at the United Nations", "United Nations", "1971-11-15", "theory-order;sovereignty-non-interference", "https://www.un.org/en/about-us/member-states/china", "China", "State practice marker on representation and participation in universal institutions."],
  ["practice-1988-peacekeeping", "China joins UN peacekeeping operations", "United Nations Peacekeeping", "1988-09-01", "use-of-force;theory-order", "https://peacekeeping.un.org/en/china", "International", "Important practice showing evolution from suspicion of intervention to active peacekeeping participation."],
  ["practice-1997-hk-handover", "Resumption of exercise of sovereignty over Hong Kong", "Government of the Hong Kong SAR", "1997-07-01", "sovereignty-non-interference;dispute-settlement", "https://www.basiclaw.gov.hk/en/index.html", "Hong Kong SAR", "Practice point for sovereignty, treaty continuity, and one country, two systems."],
  ["practice-2001-wto-membership", "China becomes a WTO member", "World Trade Organization", "2001-12-11", "global-economic-system;dispute-settlement", "https://www.wto.org/english/thewto_e/countries_e/china_e.htm", "International", "Marks China's formal integration into the WTO legal order."],
  ["practice-2008-piracy-escort", "China deploys naval escort task force to the Gulf of Aden", "Ministry of National Defense", "2008-12-26", "use-of-force;theory-order", portalUrl("China Gulf of Aden escort task force 2008 official"), "China", "Shows overseas security practice framed around UN-authorized anti-piracy cooperation."],
  ["practice-2013-bri-launch", "Belt and Road Initiative announced", "Ministry of Foreign Affairs", "2013-09-07", "belt-and-road;global-economic-system", portalUrl("Xi Jinping Silk Road Economic Belt speech 2013 official"), "China", "Starting point for BRI as a major foreign economic and legal ordering project."],
  ["practice-2015-aiib-articles", "Asian Infrastructure Investment Bank Articles of Agreement signed", "Asian Infrastructure Investment Bank", "2015-06-29", "belt-and-road;global-economic-system", "https://www.aiib.org/en/about-aiib/basic-documents/articles-of-agreement/index.html", "International", "Institution-building practice around development finance and infrastructure."],
  ["practice-2016-scs-non-appearance", "China declines to participate in South China Sea arbitration", "Permanent Court of Arbitration", "2016-07-12", "sovereignty-non-interference;dispute-settlement", "https://pca-cpa.org/en/cases/7/", "International", "Important example of non-appearance and jurisdictional objection strategy."],
  ["practice-2017-bri-forum", "First Belt and Road Forum for International Cooperation", "Belt and Road Portal", "2017-05-14", "belt-and-road;global-economic-system", "https://eng.yidaiyilu.gov.cn/", "China", "Signals BRI's transformation into a standing diplomatic and institutional platform."],
  ["practice-2020-hk-national-security-law", "Law on Safeguarding National Security in the Hong Kong SAR", "National People's Congress", "2020-06-30", "sovereignty-non-interference;sanctions-anti-sanctions", portalUrl("Hong Kong national security law 2020 NPC English"), "Hong Kong SAR", "Legal practice central to sovereignty, autonomy, sanctions, and non-interference debates."],
  ["practice-2021-sanctions-countermeasures", "China announces countermeasures against foreign sanctions", "Ministry of Foreign Affairs", "2021-03-22", "sanctions-anti-sanctions;sovereignty-non-interference", portalUrl("China countermeasures foreign sanctions March 2021 Ministry of Foreign Affairs"), "China", "Shows operational use of sanctions countermeasures alongside new domestic legislation."],
  ["practice-2022-ukraine-un-votes", "China's votes and explanations on Ukraine-related UN resolutions", "United Nations Digital Library", "2022-03-02", "use-of-force;sovereignty-non-interference", "https://digitallibrary.un.org/search?ln=en&p=China+Ukraine+vote+2022", "International", "Important practice for assessing sovereignty language, use of force, and non-alignment."],
  ["practice-2023-saudi-iran", "China facilitates Saudi-Iran rapprochement", "Ministry of Foreign Affairs", "2023-03-10", "theory-order;dispute-settlement", portalUrl("China Saudi Iran Joint Trilateral Statement 2023 MFA"), "China", "Example of China presenting itself as a mediator in regional dispute settlement."],
  ["practice-2023-bri-forum-third", "Third Belt and Road Forum for International Cooperation", "Belt and Road Portal", "2023-10-18", "belt-and-road;global-economic-system", "https://eng.yidaiyilu.gov.cn/", "China", "Shows BRI's continued diplomatic institutionalization after ten years."],
  ["practice-2024-icj-climate-statement", "China participates in ICJ climate advisory proceedings", "International Court of Justice", "2024-03-22", "global-economic-system;dispute-settlement;theory-order", "https://www.icj-cij.org/case/187", "International", "Contemporary legal practice on climate obligations and development equity."],
].map(([id, title, institution, date, topics, url, jurisdiction, note]) =>
  record({
    id,
    title,
    sourceType: "Chinese state practice",
    institution,
    date,
    topics,
    jurisdiction,
    url,
    citation: `${institution}, '${title}' (${date}).`,
    summary: note,
    note,
  }),
);

const wtoDisputes = [
  252, 309, 339, 340, 342, 358, 359, 362, 363, 373, 378, 379, 387, 394, 395,
  397, 399, 405, 413, 414, 419, 422, 425, 427, 431, 432, 437, 440, 449, 450,
  452, 460, 471, 489, 508, 509, 511, 515, 516, 517, 519, 543, 544, 562, 565,
  587, 598, 610, 611, 615, 623, 625,
].map((ds) =>
  record({
    id: `wto-ds${ds}`,
    title: `WTO dispute DS${ds} case page`,
    sourceType: "International law document",
    institution: "World Trade Organization",
    date: ds < 350 ? "2004-01-01" : ds < 450 ? "2010-01-01" : ds < 560 ? "2016-01-01" : "2022-01-01",
    topics: ["global-economic-system", "dispute-settlement"],
    jurisdiction: "International",
    url: wtoCaseUrl(ds),
    citation: `WTO, 'DS${ds}: dispute settlement case page'.`,
    summary: "WTO dispute settlement page for a China-related trade dispute or comparator dispute in China's trade-law practice.",
    note: "Useful for mapping China's use of rules-based economic dispute settlement over time.",
  }),
);

const imfRecords = [
  2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016,
  2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024,
].map((year) =>
  record({
    id: `imf-china-article-iv-${year}`,
    title: `IMF China Article IV Consultation materials (${year})`,
    sourceType: "International law document",
    institution: "International Monetary Fund",
    date: `${year}-12-31`,
    topics: ["global-economic-system"],
    jurisdiction: "International",
    url: "https://www.imf.org/en/countries/chn",
    citation: `International Monetary Fund, 'People's Republic of China: Article IV Consultation materials' (${year}).`,
    summary: "IMF surveillance materials on China's macroeconomic policy and integration into the global financial system.",
    note: "Useful for tracing how international financial institutions assess China's role in economic governance.",
  }),
);

const thinkTankRecords = [
  ["tt-merics-2023-decoupling", "MERICS China Global Competition Tracker materials", "MERICS", "2023-01-01", "global-economic-system;sanctions-anti-sanctions", "https://merics.org/en", "Think tank reporting on China, economic security, and global competition."],
  ["tt-csis-bri-reconnecting", "CSIS Reconnecting Asia project materials", "Center for Strategic and International Studies", "2023-01-01", "belt-and-road;global-economic-system", "https://reconasia.csis.org/", "Infrastructure and connectivity data useful for BRI legal and policy research."],
  ["tt-chatham-china-order", "Chatham House research on China and the international order", "Chatham House", "2023-01-01", "theory-order;use-of-force", "https://www.chathamhouse.org/topics/china", "Policy analysis on China's role in the international system."],
  ["tt-brookings-china-global-governance", "Brookings research on China and global governance", "Brookings Institution", "2022-01-01", "theory-order;global-economic-system", "https://www.brookings.edu/topic/china/", "Research materials on China's governance preferences and institutions."],
  ["tt-cfr-china-bri", "Council on Foreign Relations materials on Belt and Road", "Council on Foreign Relations", "2021-01-01", "belt-and-road;theory-order", "https://www.cfr.org/china-belt-and-road-initiative", "Explainers and analysis on BRI's international implications."],
  ["tt-carnegie-china-law-order", "Carnegie research on China and international order", "Carnegie Endowment for International Peace", "2022-01-01", "theory-order;sovereignty-non-interference", "https://carnegieendowment.org/research/china", "Research on China, order, and great-power politics."],
  ["tt-rhodium-china-economic-statecraft", "Rhodium Group research on China economic statecraft", "Rhodium Group", "2023-01-01", "global-economic-system;sanctions-anti-sanctions", "https://rhg.com/research_topic/china/", "Data-rich research on China's economy and external economic policies."],
  ["tt-odi-china-development", "ODI research on China and development cooperation", "Overseas Development Institute", "2022-01-01", "belt-and-road;global-economic-system", "https://odi.org/en/topics/china-and-international-development/", "Development policy analysis relevant to BRI and aid governance."],
  ["tt-cari-china-africa-loans", "Chinese Loans to Africa Database", "Boston University Global Development Policy Center", "2023-01-01", "belt-and-road;global-economic-system", "https://www.bu.edu/gdp/chinese-loans-to-africa-database/", "Empirical dataset for Chinese development finance and infrastructure lending."],
  ["tt-asil-china-international-law", "ASIL materials on China and international law", "American Society of International Law", "2020-01-01", "theory-order;dispute-settlement", "https://www.asil.org/", "Scholarly-practitioner materials on China-related international law developments."],
  ["tt-oxford-china-centre", "Oxford China Centre materials on law and governance", "University of Oxford China Centre", "2022-01-01", "theory-order;sovereignty-non-interference", "https://www.chinacentre.ox.ac.uk/", "Academic policy resources on Chinese governance and international relations."],
  ["tt-iiss-china-security", "IISS research on China and security", "International Institute for Strategic Studies", "2023-01-01", "use-of-force;theory-order", "https://www.iiss.org/research/china/", "Security analysis relevant to force, strategic stability, and regional order."],
  ["tt-sipri-china-security", "SIPRI research on China and security", "Stockholm International Peace Research Institute", "2023-01-01", "use-of-force;theory-order", "https://www.sipri.org/research/armament-and-disarmament/china", "Research on arms control, security, and China's military policy."],
  ["tt-unidir-china-arms-control", "UNIDIR materials on China and arms control", "UNIDIR", "2022-01-01", "use-of-force;theory-order", "https://unidir.org/", "Research relevant to China's positions on disarmament and security law."],
  ["tt-cass-international-law", "CASS Institute of International Law research portal", "Chinese Academy of Social Sciences", "2023-01-01", "theory-order;dispute-settlement", "http://iolaw.cssn.cn/", "Chinese-language research portal for international law scholarship."],
  ["tt-ciis-global-governance", "CIIS research on global governance", "China Institute of International Studies", "2023-01-01", "theory-order;global-economic-system", "https://www.ciis.org.cn/english/", "Chinese think tank analysis on global governance and diplomacy."],
  ["tt-ccg-globalization", "CCG research on globalization and China", "Center for China and Globalization", "2023-01-01", "global-economic-system;theory-order", "https://en.ccg.org.cn/", "Chinese think tank materials on globalization, trade, and governance."],
  ["tt-shanghai-institutes", "SIIS research on international order", "Shanghai Institutes for International Studies", "2023-01-01", "theory-order;belt-and-road", "https://www.siis.org.cn/", "Chinese think tank analysis on international order and cooperation."],
].map(([id, title, institution, date, topics, url, note]) =>
  record({
    id,
    title,
    sourceType: "Think tank report",
    institution,
    date,
    topics,
    jurisdiction: institution.includes("China") || institution.includes("Shanghai") ? "China" : "Foreign",
    url,
    citation: `${institution}, '${title}' (${date.slice(0, 4)}).`,
    summary: note,
    note,
  }),
);

const literatureSeeds = [
  ["lit-cohen-chiu-1974", "People's China and International Law", "Jerome Alan Cohen and Hungdah Chiu", "1974", "Book", "theory-order;sovereignty-non-interference"],
  ["lit-wang-tieya-1990", "International Law in China: Historical and Contemporary Perspectives", "Wang Tieya", "1990", "Article", "theory-order"],
  ["lit-xue-2012", "Chinese Contemporary Perspectives on International Law", "Xue Hanqin", "2012", "Book", "theory-order;sovereignty-non-interference"],
  ["lit-cai-2019", "The Rise of China and International Law", "Cai Congyan", "2019", "Book", "theory-order;dispute-settlement"],
  ["lit-chan-sovereignty", "China, State Sovereignty and International Legal Order", "Phil C W Chan", "2015", "Book", "sovereignty-non-interference;theory-order"],
  ["lit-kent-1999", "China, the United Nations, and Human Rights", "Ann Kent", "1999", "Book", "sovereignty-non-interference;theory-order"],
  ["lit-foot-2000", "Rights Beyond Borders", "Rosemary Foot", "2000", "Book", "sovereignty-non-interference;theory-order"],
  ["lit-kim-1979", "China, the United Nations and World Order", "Samuel S Kim", "1979", "Book", "theory-order;use-of-force"],
  ["lit-johnston-2008", "Social States: China in International Institutions", "Alastair Iain Johnston", "2008", "Book", "theory-order;global-economic-system"],
  ["lit-zhao-global-order", "China and the International Legal Order", "Zhao Yun", "2018", "Article", "theory-order"],
  ["lit-alden-alves-2008", "History and Identity in the Construction of China's Africa Policy", "Chris Alden and Ana Cristina Alves", "2008", "Article", "belt-and-road;global-economic-system"],
  ["lit-brautigam-2009", "The Dragon's Gift", "Deborah Brautigam", "2009", "Book", "belt-and-road;global-economic-system"],
  ["lit-jones-zeng-bri", "Understanding China's Belt and Road Initiative", "Lee Jones and Jinghan Zeng", "2019", "Article", "belt-and-road;theory-order"],
  ["lit-rudolf-2021", "The Belt and Road Initiative: Implications for the International Order", "Moritz Rudolf", "2021", "Book", "belt-and-road;theory-order"],
  ["lit-hughes-bri-law", "The Belt and Road Initiative and the Law of International Development", "Matthew S Erie", "2020", "Article", "belt-and-road;dispute-settlement"],
  ["lit-ginsburg-2019", "Authoritarian International Law?", "Tom Ginsburg", "2020", "Article", "theory-order;dispute-settlement"],
  ["lit-roberts-moraes-ferguson-2019", "Toward a Geoeconomic Order in International Trade and Investment", "Anthea Roberts, Henrique Choer Moraes and Victor Ferguson", "2019", "Article", "global-economic-system;sanctions-anti-sanctions"],
  ["lit-shaffer-gao-2018", "China's Rise: How It Took on the U.S. at the WTO", "Gregory Shaffer and Henry Gao", "2018", "Article", "global-economic-system;dispute-settlement"],
  ["lit-gao-2011", "China's Participation in the WTO", "Henry Gao", "2011", "Article", "global-economic-system;dispute-settlement"],
  ["lit-qin-2003", "WTO-Plus Obligations and Their Implications for the WTO Legal System", "Julia Ya Qin", "2003", "Article", "global-economic-system"],
  ["lit-hu-angli-2017", "China's Approach to the Use of Force", "Hu Angang", "2017", "Article", "use-of-force;theory-order"],
  ["lit-gill-huang-2009", "Sources and Limits of Chinese Soft Power", "Bates Gill and Yanzhong Huang", "2009", "Article", "theory-order;global-economic-system"],
  ["lit-davis-2021", "China's Lawfare Strategy", "Elizabeth Van Wie Davis", "2021", "Book", "sovereignty-non-interference;dispute-settlement"],
  ["lit-erickson-martinson-2019", "China's Maritime Gray Zone Operations", "Andrew S Erickson and Ryan D Martinson", "2019", "Book", "use-of-force;sovereignty-non-interference"],
  ["lit-zhang-haiwen-2016", "The South China Sea Arbitration and China's Position", "Zhang Haiwen", "2016", "Article", "sovereignty-non-interference;dispute-settlement"],
  ["lit-beckman-townsend-2017", "The South China Sea Arbitration: A Chinese Perspective", "Robert Beckman and Tara Davenport", "2017", "Article", "dispute-settlement;sovereignty-non-interference"],
  ["lit-chimni-2017", "International Institutions Today: An Imperial Global State in the Making", "B S Chimni", "2004", "Article", "theory-order;global-economic-system"],
  ["lit-sornarajah-2010", "The International Law on Foreign Investment", "M Sornarajah", "2010", "Book", "global-economic-system;belt-and-road"],
  ["lit-chaisse-2018", "China's International Investment Strategy", "Julien Chaisse", "2018", "Book", "global-economic-system;belt-and-road"],
  ["lit-van-den-bossche-2021", "The Law and Policy of the World Trade Organization", "Peter Van den Bossche and Werner Zdouc", "2021", "Book", "global-economic-system;dispute-settlement"],
  ["lit-lowenfeld-2008", "International Economic Law", "Andreas F Lowenfeld", "2008", "Book", "global-economic-system"],
  ["lit-damrosch-2021", "International Law: Cases and Materials", "Lori Fisler Damrosch and Sean D Murphy", "2021", "Book", "theory-order;use-of-force"],
  ["lit-gray-2018", "International Law and the Use of Force", "Christine Gray", "2018", "Book", "use-of-force"],
  ["lit-corten-2021", "The Law Against War", "Olivier Corten", "2021", "Book", "use-of-force"],
  ["lit-chinkin-kaldor-2017", "International Law and New Wars", "Christine Chinkin and Mary Kaldor", "2017", "Book", "use-of-force;theory-order"],
  ["lit-wang-jiangyu-economic", "China and International Economic Law", "Wang Jiangyu", "2020", "Article", "global-economic-system;theory-order"],
  ["lit-wang-jiangyu-bri", "China's Belt and Road Initiative and International Law", "Wang Jiangyu", "2021", "Article", "belt-and-road;global-economic-system"],
].map(([id, title, author, year, type, topics]) => {
  const citation = `${author}, '${title}' (${year}).`;
  return {
    bibliography: {
      id,
      title,
      author,
      date: `${year}-01-01`,
      type,
      topics,
      url: worldcatUrl(`${title} ${author}`),
      citation,
      note: "Launch bibliography item for scholarly review and expansion.",
    },
    record: record({
      id,
      title,
      sourceType: "Literature",
      institution: author,
      date: `${year}-01-01`,
      topics,
      jurisdiction: "Scholarly literature",
      url: worldcatUrl(`${title} ${author}`),
      citation,
      summary: "Scholarly work relevant to China's approach to international law and order.",
      note: "Included in the launch bibliography for review, teaching, and further annotation.",
    }),
  };
});

const records = [
  ...officialRecords,
  ...internationalRecords,
  ...statePractice,
  ...wtoDisputes,
  ...imfRecords,
  ...thinkTankRecords,
  ...literatureSeeds.map((entry) => entry.record),
];

const timeline = [
  ["tl-1945-un-charter", "1945-06-26", "UN Charter signed", "use-of-force;sovereignty-non-interference;theory-order", "intl-1945-un-charter", "Postwar legal order baseline for force, sovereignty, and collective security."],
  ["tl-1971-un-seat", "1971-10-25", "PRC seated at the United Nations", "theory-order;sovereignty-non-interference", "intl-1971-unga-2758;practice-1971-prc-un-seat", "China's representation in universal institutions shifts to the PRC."],
  ["tl-1982-unclos", "1982-12-10", "UNCLOS opened for signature", "sovereignty-non-interference;dispute-settlement", "intl-1982-unclos", "Maritime legal order becomes central to later Chinese practice."],
  ["tl-1997-hk", "1997-07-01", "Hong Kong handover", "sovereignty-non-interference;dispute-settlement", "practice-1997-hk-handover;prc-1990-basic-law-hk", "One country, two systems becomes a major sovereignty and legal-order issue."],
  ["tl-2001-wto", "2001-12-11", "China joins the WTO", "global-economic-system;dispute-settlement", "prc-2001-china-wto-accession;practice-2001-wto-membership", "China enters the multilateral trade law system."],
  ["tl-2005-anti-secession", "2005-03-14", "Anti-Secession Law adopted", "sovereignty-non-interference;use-of-force", "prc-2005-anti-secession-law", "Domestic legislation links Taiwan policy, sovereignty, and possible force."],
  ["tl-2011-peaceful-development", "2011-09-06", "Peaceful development white paper", "theory-order;use-of-force;global-economic-system", "prc-2011-peaceful-development", "China articulates a comprehensive peaceful development narrative."],
  ["tl-2013-bri", "2013-09-07", "Belt and Road Initiative announced", "belt-and-road;global-economic-system", "practice-2013-bri-launch", "BRI begins as a major ordering project."],
  ["tl-2014-scs-position", "2014-12-07", "China issues South China Sea jurisdiction position paper", "sovereignty-non-interference;dispute-settlement", "prc-2016-south-china-sea-position", "China sets out objections to arbitral jurisdiction."],
  ["tl-2015-bri-vision", "2015-03-28", "BRI Vision and Actions document issued", "belt-and-road;global-economic-system", "prc-2015-bri-vision-actions", "The initiative receives a formal policy architecture."],
  ["tl-2015-aiib", "2015-06-29", "AIIB Articles signed", "belt-and-road;global-economic-system", "practice-2015-aiib-articles", "China-backed development finance institution enters the legal landscape."],
  ["tl-2016-scs-award", "2016-07-12", "South China Sea arbitral award issued", "sovereignty-non-interference;dispute-settlement", "intl-2016-scs-award;prc-2016-scs-whitepaper", "Major inflection point in China's relationship with compulsory dispute settlement."],
  ["tl-2017-davos", "2017-01-17", "Xi Jinping speaks at Davos", "theory-order;global-economic-system", "prc-2017-xis-davos-speech", "China presents itself as a defender of globalization."],
  ["tl-2018-wto-whitepaper", "2018-06-28", "China and the WTO white paper", "global-economic-system;dispute-settlement", "prc-2018-china-wto-whitepaper", "Official account of WTO compliance and reform position."],
  ["tl-2019-trade-whitepaper", "2019-06-02", "White paper on China-US trade consultations", "global-economic-system;sanctions-anti-sanctions", "prc-2019-china-us-trade-consultations", "Trade conflict becomes central to China's critique of unilateralism."],
  ["tl-2020-export-control", "2020-10-17", "Export Control Law adopted", "sanctions-anti-sanctions;global-economic-system", "prc-2020-export-control-law", "Economic security law becomes more systematic."],
  ["tl-2021-blocking-rules", "2021-01-09", "MOFCOM blocking rules issued", "sanctions-anti-sanctions;global-economic-system", "prc-2021-blocking-rules", "China creates blocking mechanisms for foreign extraterritorial measures."],
  ["tl-2021-afsl", "2021-06-10", "Anti-Foreign Sanctions Law adopted", "sanctions-anti-sanctions;sovereignty-non-interference", "prc-2021-anti-foreign-sanctions-law", "Counter-sanctions become statutory."],
  ["tl-2022-taiwan-whitepaper", "2022-08-10", "New Taiwan white paper released", "sovereignty-non-interference;use-of-force", "prc-2022-taiwan-question-new-era", "Taiwan policy is restated in the new era vocabulary."],
  ["tl-2023-gsi", "2023-02-21", "Global Security Initiative concept paper issued", "theory-order;use-of-force", "prc-2023-global-security-initiative", "China offers a branded security governance framework."],
  ["tl-2023-saudi-iran", "2023-03-10", "Saudi-Iran rapprochement facilitated in Beijing", "theory-order;dispute-settlement", "practice-2023-saudi-iran", "China highlights mediation as order-building practice."],
  ["tl-2023-shared-future", "2023-09-26", "Community of shared future white paper", "theory-order;global-economic-system;belt-and-road", "prc-2023-global-community-shared-future", "Official normative account of China's global-order proposal."],
  ["tl-2023-bri-whitepaper", "2023-10-10", "BRI white paper released", "belt-and-road;global-economic-system", "prc-2023-bri-whitepaper", "BRI is framed as a pillar of a shared future."],
  ["tl-2024-icj-climate", "2024-03-22", "China participates in ICJ climate advisory proceedings", "global-economic-system;dispute-settlement;theory-order", "practice-2024-icj-climate-statement;intl-2024-icj-climate", "China engages legal argument on climate obligations and development equity."],
].map(([id, date, title, topics, record_ids, summary]) => ({
  id,
  date,
  title,
  topics,
  record_ids,
  summary,
}));

const bibliography = [
  ...literatureSeeds.map((entry) => entry.bibliography),
  ...thinkTankRecords.slice(0, 12).map((entry) => ({
    id: `bib-${entry.id}`,
    title: entry.title_en,
    author: entry.institution,
    date: entry.date,
    type: "Report / research portal",
    topics: entry.topics,
    url: entry.url,
    citation: entry.citation,
    note: "Think tank source included for report tracking and later item-level expansion.",
  })),
];

const oneCountryTwoSystemsTopic = "one-country-two-systems";

function addTopicToRow(row, topic) {
  const topics = new Set(String(row.topics ?? "").split(/[;|]/).filter(Boolean));
  topics.add(topic);
  row.topics = [...topics].join(";");
}

function upsertRow(rows, row) {
  const index = rows.findIndex((entry) => entry.id === row.id);
  if (index === -1) rows.push(row);
  else rows[index] = { ...rows[index], ...row };
}

for (const id of [
  "prc-1990-basic-law-hk",
  "prc-1993-whitepaper-taiwan",
  "prc-2005-anti-secession-law",
  "prc-2022-taiwan-question-new-era",
  "prc-2024-punitive-measures-taiwan",
  "practice-1997-hk-handover",
  "practice-2020-hk-national-security-law",
  "intl-1971-unga-2758",
]) {
  const row = records.find((entry) => entry.id === id);
  if (row) addTopicToRow(row, oneCountryTwoSystemsTopic);
}

for (const row of [
  record({
    id: "prc-1993-basic-law-macau",
    title: "Basic Law of the Macao Special Administrative Region",
    titleZh: "中华人民共和国澳门特别行政区基本法",
    sourceType: "PRC official document",
    institution: "National People's Congress",
    date: "1993-03-31",
    topics: ["sovereignty-non-interference", oneCountryTwoSystemsTopic, "dispute-settlement"],
    jurisdiction: "Macau SAR",
    url: "https://www.basiclaw.gov.mo/index_en.aspx",
    citation: "Basic Law of the Macao Special Administrative Region (adopted 31 March 1993).",
    summary: "Constitutional instrument for Macau's post-1999 legal order under Chinese sovereignty.",
    note: "Provides the Macau counterpart to the Hong Kong Basic Law and a comparison point for SAR autonomy.",
  }),
  record({
    id: "prc-2014-one-country-two-systems-hk",
    title: "The Practice of the One Country, Two Systems Policy in the Hong Kong Special Administrative Region",
    titleZh: "“一国两制”在香港特别行政区的实践",
    sourceType: "PRC official document",
    institution: "State Council Information Office",
    date: "2014-06-10",
    topics: ["sovereignty-non-interference", oneCountryTwoSystemsTopic, "dispute-settlement"],
    jurisdiction: "Hong Kong SAR",
    url: "https://english.www.gov.cn/archive/white_paper/2014/08/23/content_281474982986578.htm",
    citation:
      "State Council Information Office, 'The Practice of the One Country, Two Systems Policy in the Hong Kong Special Administrative Region' (10 June 2014).",
    summary: "White paper setting out the central government account of one country, two systems in Hong Kong.",
    note: "Key official interpretation of autonomy, central authority, and the constitutional basis of Hong Kong governance.",
  }),
  record({
    id: "practice-1999-macau-handover",
    title: "Resumption of exercise of sovereignty over Macao",
    sourceType: "Chinese state practice",
    institution: "Government of the Macao SAR",
    date: "1999-12-20",
    topics: ["sovereignty-non-interference", oneCountryTwoSystemsTopic, "dispute-settlement"],
    jurisdiction: "Macau SAR",
    url: "https://www.gov.mo/en/about-macao/",
    citation: "Government of the Macao SAR, 'About Macao' (accessed as official background material).",
    summary: "State practice marker for Macau under one country, two systems after 20 December 1999.",
    note: "Completes the SAR comparison by pairing Macau practice with Hong Kong practice.",
  }),
  record({
    id: "practice-2021-macau-national-security",
    title: "Macao national security legal framework materials",
    sourceType: "Chinese state practice",
    institution: "Government of the Macao SAR",
    date: "2021-01-01",
    topics: ["sovereignty-non-interference", oneCountryTwoSystemsTopic, "sanctions-anti-sanctions"],
    jurisdiction: "Macau SAR",
    url: "https://www.gov.mo/en/",
    citation: "Government of the Macao SAR, 'Macao national security legal framework materials' (official portal).",
    summary: "Official materials relevant to Macau national security law and SAR governance.",
    note: "Useful comparator for Hong Kong national security debates under one country, two systems.",
  }),
]) {
  upsertRow(records, row);
}

for (const id of ["tl-1997-hk", "tl-2005-anti-secession", "tl-2022-taiwan-whitepaper"]) {
  const row = timeline.find((entry) => entry.id === id);
  if (row) addTopicToRow(row, oneCountryTwoSystemsTopic);
}

for (const row of [
  {
    id: "tl-1993-macau-basic-law",
    date: "1993-03-31",
    title: "Macau Basic Law adopted",
    topics: `sovereignty-non-interference;${oneCountryTwoSystemsTopic}`,
    record_ids: "prc-1993-basic-law-macau",
    summary: "The Macau SAR constitutional framework is adopted before the 1999 handover.",
  },
  {
    id: "tl-1999-macau",
    date: "1999-12-20",
    title: "Macau handover",
    topics: `sovereignty-non-interference;${oneCountryTwoSystemsTopic};dispute-settlement`,
    record_ids: "practice-1999-macau-handover;prc-1993-basic-law-macau",
    summary: "Macau becomes the second SAR governed under one country, two systems.",
  },
  {
    id: "tl-2014-hk-whitepaper",
    date: "2014-06-10",
    title: "Hong Kong one country, two systems white paper released",
    topics: `sovereignty-non-interference;${oneCountryTwoSystemsTopic};dispute-settlement`,
    record_ids: "prc-2014-one-country-two-systems-hk",
    summary: "The State Council presents an official interpretation of central authority and Hong Kong autonomy.",
  },
  {
    id: "tl-2020-hk-national-security",
    date: "2020-06-30",
    title: "Hong Kong national security law adopted",
    topics: `sovereignty-non-interference;${oneCountryTwoSystemsTopic};sanctions-anti-sanctions`,
    record_ids: "practice-2020-hk-national-security-law",
    summary: "National security becomes a central controversy in the legal meaning of one country, two systems.",
  },
]) {
  upsertRow(timeline, row);
}

for (const id of ["lit-chan-sovereignty", "lit-kent-1999"]) {
  const row = bibliography.find((entry) => entry.id === id);
  if (row) addTopicToRow(row, oneCountryTwoSystemsTopic);
}

for (const row of [
  {
    id: "lit-gittings-2016-hk",
    title: "Introduction to the Hong Kong Basic Law",
    author: "Danny Gittings",
    date: "2016-01-01",
    type: "Book",
    topics: `${oneCountryTwoSystemsTopic};sovereignty-non-interference;dispute-settlement`,
    url: "https://search.worldcat.org/search?q=Introduction%20to%20the%20Hong%20Kong%20Basic%20Law%20Danny%20Gittings",
    citation: "Danny Gittings, 'Introduction to the Hong Kong Basic Law' (2016).",
    note: "Launch bibliography item for Hong Kong Basic Law and autonomy research.",
  },
  {
    id: "lit-chen-2021-hk",
    title: "The Changing Legal Orders in Hong Kong and China",
    author: "Albert H Y Chen",
    date: "2021-01-01",
    type: "Book / scholarship",
    topics: `${oneCountryTwoSystemsTopic};sovereignty-non-interference;dispute-settlement`,
    url: "https://search.worldcat.org/search?q=Albert%20H%20Y%20Chen%20Hong%20Kong%20Basic%20Law%20one%20country%20two%20systems",
    citation: "Albert H Y Chen, 'The Changing Legal Orders in Hong Kong and China' (2021).",
    note: "Launch bibliography item for legal change under one country, two systems.",
  },
  {
    id: "lit-lo-2020-macau",
    title: "The Legal System of Macao and One Country, Two Systems",
    author: "Macao SAR legal scholarship",
    date: "2020-01-01",
    type: "Literature / research lead",
    topics: `${oneCountryTwoSystemsTopic};sovereignty-non-interference`,
    url: "https://search.worldcat.org/search?q=Macao%20one%20country%20two%20systems%20legal%20system",
    citation: "Macao SAR legal scholarship, 'The Legal System of Macao and One Country, Two Systems' (2020).",
    note: "Research lead for adding Macau-focused scholarship during editorial review.",
  },
]) {
  upsertRow(bibliography, row);
}

mkdirSync(dataDir, { recursive: true });
writeFileSync(join(dataDir, "records.csv"), toCsv(records, recordsHeaders));
writeFileSync(join(dataDir, "timelines.csv"), toCsv(timeline, timelineHeaders));
writeFileSync(join(dataDir, "bibliography.csv"), toCsv(bibliography, bibliographyHeaders));

console.log(`Seeded ${records.length} records, ${timeline.length} timeline entries, and ${bibliography.length} bibliography entries.`);
